
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            android-client-id: ${GOOGLE_ANDROID_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
  mail:
    username: ${MAIL_USERNAME}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          starttls:
            enable: "true"
          auth: "true"
    host: ${MAIL_HOST}
    password: ${MAIL.PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: "false"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
    web:
      pageable:
        one-indexed-parameters: "true"
  application:
    name: grocery_store
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  devtools:
    restart:
      enabled: false
  cache:
    type: redis
  main:
    banner-mode: off

jwt:
  accesstoken-validity-in-seconds: ${JWT_ACCESS_TOKEN_EXPIRY}
  refreshtoken-validity-in-seconds: ${JWT_REFRESH_TOKEN_EXPIRY}
  base64-secret: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    enabled: "true"
  swagger-ui:
    enabled: "true"
    url: /v3/api-docs

vnpay:
  pay-url: ${VNPAY_API_URL}
  return-url: ${VNPAY_RETURN_URL}
  tmn-code: ${VNPAY_TMN_CODE}
  secret-key: ${VNPAY_SECRET_KEY}
  version: ${VNPAY_VERSION}
  command: ${VNPAY_COMMAND}
  order-type: ${VNPAY_ORDER_TYPE}
  success-url: ${VNPAY_SUCCESS_URL}
  failure-url: ${VNPAY_FAILURE_URL}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  default-folder: ${CLOUDINARY_UPLOAD_FOLDER:grocery_store}

cors:
  client1: ${CORS}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}
    model-id: ${GEMINI_API_MODEL_ID}